### ISSUE TITLE
Media queries

### ISSUE THREAD

**Issue by ConnerPetzold** [cssinjs/aphrodite-jss#1]
Hey I'm playing around with using this in a project (I replaced aphrodite because I wanted JSS plugins). I was hoping to start a discussion about media queries.

Do you have any ideas on how this would be done?

Also, somewhat related.. I've tweaked the `css` function a bit to allow something like `css(styles.foo, css(styles.bar))`, but it relies on an ugly hack which essentially caches the original object name and rule set. I'd love to submit a PR for something like that, but would be interested in hearing about the media query approach because it will most likely break my naive changes.

**Comment by kof** [comment]
Here is the issue about media queries, it is in work https://github.com/cssinjs/jss/issues/246

Regarding `css(styles.foo, css(styles.bar))` please create a separate issue and start with explaining your use case, not the solution.
