### ISSUE TITLE
Keyframes

### ISSUE THREAD

**Issue by natew** [cssinjs/aphrodite-jss#13]
Attempting to do a simple keyframe animation, just curious how this would work through aphrodite-jss.

**Comment by kof** [comment]
Did you try? Didn't work? Can you make your question very specific and if there is a bug provide something reproducible?

**Comment by natew** [comment]
Ah ok, I tried something simple but didn't work, and then didn't see docs. I'm using a library on top, so may need to implement it there. Will close once I verify

**Comment by JamesHisTheKing** [comment]
what is the syntax plaese?
