### ISSUE TITLE
Can't edit styles in Chrome

### ISSUE THREAD

**Issue by natew** [cssinjs/aphrodite-jss#14]
Just curious, is this avoidable?

![image](https://cloud.githubusercontent.com/assets/12100/26086553/3e99ef48-39a0-11e7-8b7c-0fe4ac86721d.png)

I can't edit any JSS styles because they are greyed out for some reason.

**Comment by kof** [comment]
Yes, this happens, when  .insertRule API is used, also you don't see the css rules in the head. I was thinking to add a fix for dev environment as this is only a problem during development.

**Comment by kof** [comment]
Created a specific issue for this https://github.com/cssinjs/jss/issues/491
