### ISSUE TITLE
Unable to render media queries

### ISSUE THREAD

**Issue by tiagojsalmeida** [cssinjs/aphrodite-jss#4]
Hey guys.

I'm not sure why but I'm unable to render media queries.

Can I not render my media queries like this?
```
css(StyleSheet.create({
  base: {
    '@media only screen and (min-width: 1024px)': {
      width: px(20),
    }
  }
}).base)
```

**Comment by kof** [comment]
Take a look at the example, it should work ...

**Comment by kof** [comment]
Just tried to be sure and it turns a bug, interesting thing is that this works:

``` javascript
{
  base: {
    float: 'left',
    '@media only screen and (min-width: 1024px)': {
      width: px(20),
    }
  }
}
```

**Comment by tiagojsalmeida** [comment]
@kof that works because there's the `float: left`. 
From my investigation, whenever you just have media queries, they will become empty, therefore the styles will be empty which causes this bug.
This occurs with one of the plugins but I didn't figure out which.

**Comment by kof** [comment]
Moved this issue to jss issue tracker, because its not related to this code base.
