### ISSUE TITLE
Outdated node engine specified in package.json

### ISSUE THREAD

**Issue by cryptoquick** [cssinjs/aphrodite-jss#9]
Is there a reason the package.json specifies that this package is incompatible with Node 7? This outright breaks a yarn install.

**Comment by spadin** [comment]
Have the same issue. I used `yarn add aphrodite-jss --ignore-engines` and it works, but it's annoying because I have to use `--ignore-engines` for any other `yarn` install going forward as well. Made a PR to remove this requirement.

**Comment by kof** [comment]
I think we can do the same we did for the jss core https://github.com/cssinjs/jss/blob/master/package.json#L27 because node is for devDependencies only.

**Comment by kof** [comment]
merged, published v1.0.3
